name: Auto approve

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Abildin/auto-approve-action@develop
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        allowed-authors: '.github/configs/allowed-authors.json'
        allowed-files: '.github/configs/allowed-files.json'