name: Auto approve

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Abildin/auto-approve-action@approve-revert-prs
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        config: '.github/configs/auto-approve.json'
