name: Auto approve

env:
  BASE_REF: ${{ github.base_ref }}
  HEAD_REF: ${{ github.head_ref }}
  TARGET_FILES: |
    requirements.txt

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Abildin/auto-approve-action@develop
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/github-script@v3
      with:
        script: |
          const commits_url = context.payload.pull_request.commits_url
          const result = await github.request(commits_url)
          console.log(result)

