name: Auto approve

env:
  BASE_REF: ${{ github.base_ref }}
  HEAD_REF: ${{ github.head_ref }}
  TARGET_FILES: |
    requirements.txt

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check auto approve conditions
      run: |
        bash .github/scripts/check-auto-approve.sh
    - uses: hmarr/auto-approve-action@v2.0.0
      if: success()
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"